codestates-seb/seb43_main_006

client/src/pages/Login.tsx

`fe-feat/setting/#18` -> `fe`
- 로그인 페이지 디자인 수정
- 로그인 페이지 버튼 수정
- 배경 이미지 추가

Feat: 로그인 페이지 2차 수정 및 추가 구현

---

client/src/pages/Signup.tsx

`fe-feat/setting/#19` -> `fe`
- 회원가입 페이지 디자인수정
- 배경이미지 추가
- 유효성 검사 추가
- 유효성 검사 일부가 아직 미완성이며, 이후에 추가 혹은 변경될 수 있음
- 약관의 내용은 예시이며 문법적으로도 문제가 많음

Feat: 회원가입 페이지 2차 수정 및 추가

---

server/src/main/java/com/codestates/julsinsa/helper/event/MemberRegistrationApplicationEvent.java
server/src/main/java/com/codestates/julsinsa/member/controller/MemberController.java
server/src/main/java/com/codestates/julsinsa/member/dto/FindDto.java
server/src/main/java/com/codestates/julsinsa/member/mapper/MemberMapper.java
server/src/main/java/com/codestates/julsinsa/member/repository/MemberRepository.java
server/src/main/java/com/codestates/julsinsa/member/service/MemberService.java

Branch
be-feat/member-> be
변경 사항
아이디 찾기 구현
비밀번호 찾기 구현
유의사항

feat : 아이디 찾기 , 비밀번호 찾기 구현

---

server/src/main/java/com/codestates/julsinsa/helper/email/EmailConfiguration.java
server/src/main/java/com/codestates/julsinsa/helper/email/HtmlEmailSendable.java
server/src/main/java/com/codestates/julsinsa/helper/event/MemberRegistrationEventListener.java
server/src/main/java/com/codestates/julsinsa/member/service/MemberService.java

Branch
be-feat/member-> be
변경 사항
메일 보내는 형식을 html로 구현
능력껏 꾸며봄^^
유의사항
꾸미는건 css로 했음!

feat : 메일 보내는 형식을 html로 구현 + 이쁘게 보내도록 수정

---

client/src/components/Common/Button.tsx

`fe-feat/setting/#83` -> `fe`
- Dark 버튼 구현
- Light 버튼 구현
- 공통 Button 컴포넌트 사용시 필요한 Props를 확인하고 사용할 것!
- 사용하다 문제 및 피득백 발생 시 공유해 줄 것!

feat: 공통 컴포넌트 버튼 구현

---

client/src/types/Interfaces.ts

`fe-feat/button/#83` -> `fe`
- Button Props type 변경

fix: Button props type 변경

---

client/src/pages/Signup/SignupInput.tsx
client/src/pages/Signup/SignupSelection.tsx
client/src/pages/Signup/SignupTerm.tsx

`fe-feat/button/#91` -> `fe`
- selection 페이지 contents 배경을 white, 기본 회원가입 버튼을 themeColor로 변경
- term 페이지 border와 padding을 추가 콘텐츠의 구분감 부여
- input 페이지 number 유효성 검사 추가 및 회원가입 성공후 navigate("/") 설정

Feat: 회원가입 관련 페이지 수정 및 추가

---

client/src/App.tsx
client/src/pages/Login/FindEmail.tsx
client/src/pages/Login/FindPassword.tsx
client/src/pages/Login/Login.tsx

`fe-feat/button/#91` -> `fe`
- 로그인 페이지 가로 길이 700px -> 600px
- 폰트 사이즈 감소
- padding, margin 축소
- signup 페이지 경로 /signup/selelction -> /signup으로 변경

Fix: 로그인 페이지 스타일 수정

---

server/src/main/java/com/codestates/julsinsa/advice/GlobalExceptionAdvice.java
server/src/main/java/com/codestates/julsinsa/item/controller/ItemController.java
server/src/main/java/com/codestates/julsinsa/item/dto/ItemDto.java
server/src/main/java/com/codestates/julsinsa/item/entity/Item.java
server/src/main/java/com/codestates/julsinsa/item/mapper/ItemMapper.java
server/src/main/java/com/codestates/julsinsa/item/repository/FavoriteRepository.java
server/src/main/java/com/codestates/julsinsa/item/repository/ItemRepository.java
server/src/main/java/com/codestates/julsinsa/item/service/ItemService.java
server/src/main/java/com/codestates/julsinsa/member/controller/MemberController.java
server/src/main/java/com/codestates/julsinsa/member/dto/EmailRequest.java
server/src/main/java/com/codestates/julsinsa/member/dto/FindDto.java
server/src/main/java/com/codestates/julsinsa/member/dto/MemberDto.java
server/src/main/java/com/codestates/julsinsa/member/service/MemberService.java
server/src/main/java/com/codestates/julsinsa/response/ErrorResponse.java
server/src/main/java/com/codestates/julsinsa/review/dto/ReviewDto.java
server/src/main/java/com/codestates/julsinsa/review/mapper/ReviewMapper.java
server/src/main/java/com/codestates/julsinsa/review/service/ReviewService.java
server/src/main/resources/db/h2/data.sql

Branch
Be-feat -> be
변경 사항
찜 목록 불러오는 데이터 추가 ( 사진 )
유효성 규칙 추가 ( 비밀번호 등등.. )
유효성 예외 처리 로직 추가
item 데이터 타입 몇가지 수정
유의사항

Fix: 찜 목록 불러오는 데이터 추가 , 유효성 규칙 추가 , 유효성 예외 처리 로직 추가

---

client/src/pages/Login/FindEmail.tsx
client/src/pages/Login/FindPassword.tsx
client/src/pages/Login/Login.tsx
client/src/pages/Signup/SignupInput.tsx
client/src/pages/Signup/SignupSelection.tsx
client/src/pages/Signup/SignupTerm.tsx

`fe-feat/주류리스트/#103` -> `fe`
- 로그인 회원가입 페이지 icon 크기 40px
- 버튼 font size 18px
- 경로 수정
- test url env를 사용해 가져오도록 수정

Fix: 로그인-회원가입 페이지 스타일 및 경로 수정

---

client/src/pages/Login/Login.tsx
client/src/redux/slice/store.tsx

`fe-feat/redux/#107` -> `fe`
- 리덕스 상태 저장 로직 수정
- 리덕스 로그아웃 로직 수정
- memberId 로컬 저장소에 저장

Feat: Redux 로직 추가 및 변경

---

client/src/components/AlcoholPage/AlcoholList.tsx
client/src/components/AlcoholPage/SortingUtils.tsx
client/src/hooks/useAxios.tsx
client/src/pages/Alcohol.tsx
client/src/types/AlcholInterfaces.ts

`fe-feat/주류리스트/#105` -> `fe`
- 주류 리스트 정렬 드롭다운 메뉴 구현
- 카테고리별 아이템 정렬 기능

Feat: 주류 리스트 정렬 드롭다운 메뉴 구현

---

client/src/pages/Mypage/changeinfo.tsx
client/src/pages/Mypage/likepage.tsx

- 찜리스트 페이지 페이지네이션 구현
- 개인정보 수정 페이지 기존의 에러 수정
- 개인정보 수정 페이지 기능 추가

Feat: 찜리스트 페이지 페이지네이션 구현 및 개인정보수정페이지 에러수정 및 기능 추가

---

client/package-lock.json
client/package.json
client/public/index.html
client/src/pages/Map.tsx
client/src/pages/Mypage/likepage.tsx
client/src/pages/Place.tsx

`fe-feat-map` -> `fe`
-  카카오지도 연결
- map 컴포넌트 생성
- 코드 작업중 npm install dotenv했음. 
- env 파일에 REACT_APP_KAKAO_MAP_KEY 값 들어가야함.

Feat: 카카오맵 지도 연결

---

client/src/hooks/useAxiosAll.ts
client/src/pages/Login/FindEmail.tsx
client/src/pages/Login/FindPassword.tsx
client/src/pages/Login/Login.tsx
client/src/pages/Mypage/changeinfo.tsx
client/src/pages/Signup/SignupInput.tsx

`fe-feat/주류리스트/#113` -> `fe`
-  useAxiosAll 구현
- 로그인, 회원가입, 이메일 찾기, 아이디 찾기, 개인정보 수정 페이지에서의 axios 요청 수정 및 useAxiosAll 적용
- 아직 구현중에 있으며 토큰 재발급 및 재요청 로직은 아직 동작 확인이 부족한 상태

Feat: useAxiosAll 구현 및 axios 요청 적용

---

server/src/main/java/com/codestates/julsinsa/auth/filter/JwtAuthenticationFilter.java
server/src/main/java/com/codestates/julsinsa/auth/filter/JwtVerificationFilter.java
server/src/main/java/com/codestates/julsinsa/auth/handler/OAuth2MemberSuccessHandler.java
server/src/main/java/com/codestates/julsinsa/auth/jwt/JwtTokenizer.java
server/src/main/java/com/codestates/julsinsa/cart/controller/CartController.java
server/src/main/java/com/codestates/julsinsa/cart/dto/CartDto.java
server/src/main/java/com/codestates/julsinsa/cart/dto/ItemCartDto.java
server/src/main/java/com/codestates/julsinsa/cart/entity/Cart.java
server/src/main/java/com/codestates/julsinsa/cart/entity/ItemCart.java
server/src/main/java/com/codestates/julsinsa/cart/mapper/CartMapper.java
server/src/main/java/com/codestates/julsinsa/cart/repository/CartRepository.java
server/src/main/java/com/codestates/julsinsa/cart/service/CartService.java
server/src/main/java/com/codestates/julsinsa/config/SecurityConfiguration.java
server/src/main/java/com/codestates/julsinsa/exception/ExceptionCode.java
server/src/main/java/com/codestates/julsinsa/item/controller/ItemController.java
server/src/main/java/com/codestates/julsinsa/item/entity/Item.java
server/src/main/java/com/codestates/julsinsa/item/repository/ItemRepository.java
server/src/main/java/com/codestates/julsinsa/item/service/ItemService.java
server/src/main/java/com/codestates/julsinsa/member/controller/MemberController.java
server/src/main/java/com/codestates/julsinsa/member/dto/MemberDto.java
server/src/main/java/com/codestates/julsinsa/member/entity/Member.java
server/src/main/java/com/codestates/julsinsa/member/mapper/MemberMapper.java
server/src/main/java/com/codestates/julsinsa/member/service/MemberService.java
server/src/main/resources/db/h2/data.sql

Branch
Be-feat/member -> be
변경 사항
장바구니 엔티티 추가 , 컨트롤러 get , post만 구현
유의사항

Feat: 장바구니 추가

---

client/src/App.tsx
client/src/hooks/useAxiosAll.ts
client/src/pages/Login/FindEmail.tsx
client/src/pages/Login/FindPassword.tsx
client/src/pages/Login/Login.tsx
client/src/pages/Mypage/changeinfo.tsx
client/src/pages/Signup/SignupInput.tsx
client/src/redux/slice/store.tsx

`fe-feat/주류리스트/#120` -> `fe`
-  useAxiosAll 구현 409-401 에러 코드 확인후 토큰 갱신& 재요청 분기 추가
- app.tsx import 구분 주석 Pages 추가
- 로그아웃 상태 변경 함수 refresh 토큰 제거 추가
- 로그인 시 refresh 토큰 로컬 저장 추가

Feat: useAxiosAll 에러 상태 확인후 토큰 갱신 및 재요청 로직 추가

---

client/src/components/AlcoholDetailPage/AlcoholItem.tsx
client/src/components/AlcoholDetailPage/QuantityControl.tsx
client/src/pages/AlcoholDetail.tsx
client/src/services/api/alcoholListAPI.ts
client/src/types/AlcholInterfaces.ts

`fe-feat/주류리스트/#105` -> `fe`
- 서버에서 데이터 가져오기
- 수량 컴포넌트 제작
- 데이터 아이디 및 데이터 넘겨주기

Feat: 주류 상세데이터 결제 페이지 props 전달

---

client/src/components/Common/AlertModal.tsx
client/src/pages/Login/FindPassword.tsx
client/src/types/Interfaces.ts

`fe-feat/주류리스트/#126` -> `fe`
-  모달 랜더시 주변 배경 명도 감소 처리
- 모달 배경 색 및 정렬 변경
- title props 추가
- onClick 핸들러 2개 받도록 함 (취소, 확인)
- 문자열(text) props 넘겨주실 때 개행하실때 \을 넣어주시면 됩니다.

Feat: 모달 공통 컴포넌트 구현 및 기능 추가

---

client/src/components/AlcoholDetailPage/AlcoholItem.tsx
client/src/components/AlcoholPage/AlcoholListItem.tsx
client/src/components/Common/ClickFavoriteItem.tsx
client/src/services/api/alcoholListAPI.ts
client/src/services/api/axiosInstance.ts
client/src/types/AlcholInterfaces.ts

`fe-feat/주류리스트/#105` -> `fe`
- 결제 페이지 props 변경
- Token 인스턴스 설정
- 아이템 찜 구현

Feat: 주류 아이템 찜 구현

---

client/src/pages/Map.tsx
client/src/pages/MarkerData.js
client/src/pages/Place.tsx

`fe-feat/map` -> `fe`
-  지도페이지 사용자 현재위치 조회 기능추가
- 지도페이지 마커 기능 추가
- 지도페이지 커스텀어레이 기능 추가
- 마커에 필요한 데이터내용 추가
- 기능만 추가된 상태임. 디자인은 아직 안 다듬음.

Feat: 지도페이지 사용자 현재위치조회 및 커스텀어레이 기능 추가

---

client/src/pages/Map.tsx
client/src/pages/Place.tsx

`fe-feat-map` -> `fe`
-  마커에 필요한 더미데이터 연결
- 디자인정리
- 장바구니로 페이지만 넘어가고 기능연결은 안되어있음.

Feat: 지도페이지 더미데이터 연결 및 디자인 정리 

---

client/package-lock.json
client/package.json
client/src/App.tsx
client/src/pages/Payment/Checkout.tsx
client/src/pages/Payment/Fail.tsx
client/src/pages/Payment/Payment.tsx
client/src/pages/Payment/PaymentUserinfo.tsx
client/src/pages/Payment/Paymentitemlist.tsx
client/src/pages/Payment/Paymentpayinfo.tsx
client/src/pages/Payment/Progress.tsx
client/src/types/AlcholInterfaces.ts

`fe-feat/paymentpage` -> `fe`
- 날짜 클릭시 날짜를 선택할 수 있는 토글 생성
- 컴포넌트 분리
- 결제하기 버튼으로 토스 페이먼츠 api와 연결
- 결제api의 결과에 따라 success 페이지와 fail 페이지로 이동
- 결제시스템을 테스트모드로 했으나 실제로 결제를 해보진 않았음.

feat: 결제페이지 구현

---

client/src/pages/Map.tsx
client/src/pages/Mypage/likepage.tsx
client/src/pages/Mypage/orderpage.tsx
client/src/pages/Place.tsx
client/src/redux/slice/store.tsx

`fe-feat-mypage` -> `fe`
-  찜리스트 디자인 수정
- 주문내역 디자인 수정

Feat: 마이페이지 디자인 수정

---

client/src/components/AlcoholDetailPage/AlcohoItemContent.tsx
client/src/components/AlcoholDetailPage/AlcoholItemBuy.tsx
client/src/components/AlcoholPage/AlcoholListItem.tsx
client/src/components/Common/PriceDisplay.tsx
client/src/components/Common/PriceRegular.tsx
client/src/utils/priceUtils.ts

`fe-feat/주류리스트/#137` -> `fe`
- 추천 상품 화살표 특정 개수 이하일 때는 없게끔 수정
- Price 정규표현식 수정

Fix: 상세 페이지 추천 상품 화살표 스크롤 수정

---

client/src/pages/Map.tsx
client/src/pages/Place.tsx
client/src/redux/slice/store.tsx

`fe-feat/map-map` -> `fe`
- 지도페이지 매장 선택버튼 클릭시 상태관리 기능 구현

Feat: 지도페이지 매장선택 구현 

---

client/src/components/AlcoholPage/SortingUtils.tsx
client/src/services/api/alcoholListAPI.ts

`fe-feat/refactor/#151` -> `fe`
- 주류 리스트 카테고리 리팩토링
- 주류 API 인스턴스 리팩토링

Refactor: 주류 리스트 카테고리 및 주류 API 인스턴스 리팩토링

---

client/.eslintrc.json
client/craco.config.js
client/package-lock.json
client/package.json
client/src/App.tsx
client/src/components/Chat/ChatComponent.tsx
client/src/hooks/useAxiosAll.tsx
client/src/pages/Login/FindEmail.tsx
client/src/pages/Login/FindPassword.tsx
client/src/pages/Login/Login.tsx
client/src/pages/Mypage/changeinfo.tsx
client/src/pages/Signup/SignupInput.tsx
client/src/pages/Signup/SignupTerm.tsx
client/tsconfig.json
client/tsconfig.paths.json

`fe-feat/path-alias/#150` -> `fe`
-  path alias 설정 및 기타 관련 alias 적용해 경로 표현
- craco, tsconfig-paths-webpack-plugin 설치
- eslint es5 문법으로 모듈 호출 가능하도록 수정
- src를 기본 최상위 경로로 정의하였으며, 각자의 필요에 따라 tsconfig.paths.json에 경로 alias에서 선언해 사용가능
- 모르겠으면 물어봐주세요!

Feat: alias path 설정 및 적용

---

client/package-lock.json
client/package.json
client/src/pages/Payment/Checkout.tsx
client/src/pages/Payment/Fail.tsx
client/src/pages/Payment/Payment.tsx
client/src/pages/Payment/PaymentConfirm.tsx
client/src/pages/Payment/PaymentUserinfo.tsx

`fe-feat/paymentpage`->` fe`
- 상태 끌어올리기 수정
- 안쓰는 코드들 삭제
- 이름이 변경되는건 삭제안했음.

fix: 결제 상태끌어올리기 수정

---

client/craco.config.js
client/package-lock.json
client/package.json
client/tsconfig.json

`fe-feat/path-alias/#150` -> `fe`
- path alias 버그 수정
- craco, cracoAlias 설치

Fix: Alias Craco 버그 수정

---

client/package-lock.json
client/package.json
client/public/index.html
client/src/App.tsx
client/src/pages/Payment/Checkout.tsx
client/src/pages/Payment/CheckoutChang.tsx
client/src/pages/Payment/Payment.tsx
client/src/pages/Payment/PaymentConfirm.tsx
client/src/pages/Payment/PaymentUserinfo.tsx
client/src/pages/Payment/Progress.tsx

`fe-feat/pay` -> `fe`
- 결제 위젯에서 창으로 변경
- 테스트 결제까지 완료
- 서버와 연결은 아직 안했음.

Fix: 결제 창으로 변경

---

client/src/hooks/useAxiosAll.tsx
client/src/pages/Home.tsx
client/src/pages/Login/Login.tsx

`fe-feat/token` -> `fe`
- 토큰 저장 밋 사용 방식 수정
- Bearer 제거

fix: 토큰 저장 및 사용 방식 수정

---

server/src/main/java/com/codestates/julsinsa/auth/filter/JwtAuthenticationFilter.java
server/src/main/java/com/codestates/julsinsa/auth/handler/OAuth2MemberSuccessHandler.java
server/src/main/java/com/codestates/julsinsa/cart/mapper/CartMapper.java
server/src/main/java/com/codestates/julsinsa/item/dto/ItemDto.java
server/src/main/java/com/codestates/julsinsa/item/entity/Favorite.java
server/src/main/java/com/codestates/julsinsa/item/entity/Item.java
server/src/main/java/com/codestates/julsinsa/item/repository/FavoriteRepository.java
server/src/main/java/com/codestates/julsinsa/member/service/MemberService.java
server/src/main/java/com/codestates/julsinsa/order/entity/Order.java
server/src/main/java/com/codestates/julsinsa/review/dto/ReviewDto.java
server/src/main/java/com/codestates/julsinsa/review/repository/ReviewRepository.java
server/src/main/java/com/codestates/julsinsa/review/service/ReviewService.java
server/src/main/resources/application.yml
server/src/main/resources/db/h2/data.sql

Branch
Be-feat/member -> be
변경 사항
OAuth2 로그인 토큰 만료시간,발행시간 추가
기존 로그인과 OAuth2 로그인 토큰 만료시간,발행시간 형식 수정
각 엔티티마다 유효성 규칙 추가
유의사항

Fix: 기존 로그인과 OAuth2 로그인 토큰 만료시간,발행시간 형식 수정 , 유효성 규칙 추가

---

client/src/components/Common/AlertModal.tsx
client/src/components/Common/Button.tsx
client/src/components/HelpCenter/AnswerContainer.tsx
client/src/index.tsx
client/src/pages/HelpCenter.tsx
client/src/pages/Home.tsx
client/src/pages/Login/Login.tsx

`fe-feat/customer-center/156` -> `fe`
- 고객센터 페이지 구현
- import 경로 수정
- 오어스 로그인 성공시 home 확면 url 정리로 / navigate

Feat: 고객페이지 구현 및 import 경로 수정

---

client/src/layout/Header/index.tsx
client/src/layout/Main/index.tsx

`fe-feat/Headerlayout` ->`fe`
- 동적인 css 요소 추가
- 네이게이션 추가
- li 요소 갱신
- 로그인 로그아웃 버튼 구현
- 콘솔 버그 수정
- 
- 반응형해야함

Fix: Header navigate 및 css 수정

---

client/src/pages/Map.tsx
client/src/pages/Mypage/likepage.tsx
client/src/pages/Mypage/orderpage.tsx

- 찜리스트 기능 구현 및 장바구니 연결
- 주문내역 더미데이터 연결 후 코드 정리

Feat: 마이페이지 기능 구현

---

client/src/App.tsx
client/src/pages/Mypage/likepage.tsx
client/src/pages/Mypage/orderpage.tsx
client/src/redux/slice/store.tsx

- 찜리스트 장바구니버튼 기능 구현
- 찜리스트 삭제버튼기능 구현
- 주문내역페이지 기간에 따른 조회버튼 기능 구현
- 마이페이지 파일명 소문자에서 대문자로 부분변경
- 로그인시  Bearer부분 토큰에서 생략부분 수정
깃헙 오류로 인해 브랜치명이 좀 이상한 점에 대해 양해바랍니다.

Feat: 찜리스트, 주문내역 페이지기능 구현 마무리 

---

client/src/pages/Cart.tsx

`fe-feat/Cartfix` -> `fe`
- 고객센터 페이지 구현

Fix: Cart 토큰 수정

---

client/src/App.tsx
client/src/pages/Mypage/ChangeInfoPage.tsx
client/src/pages/Mypage/LikeListPage.tsx
client/src/pages/Mypage/OrderListPage.tsx

- 찜리스트, 주문내역페이지, 회원정보수정페이지 파일명 변경
깃헙 오류로 인해 브랜치명이 좀 이상한 점에 대해 양해바랍니다.

Rename: 파일명 변경

---

client/src/pages/Map.tsx
client/src/pages/Mypage/LikeListPage.tsx
client/src/pages/Mypage/OrderListPage.tsx
client/src/pages/Place.tsx

`fe-feat-mypage` -> `fe`
- 서버주소 변경 및 결제삭제 기능 구현중
결제삭제 기능 구현중.

Feat: 서버주소 변경 및 결제삭제 기능 구현중

---

client/src/hooks/useAxiosAll.tsx
client/src/pages/Login/Login.tsx
client/src/pages/Signup/SignupInput.tsx
client/src/pages/Signup/SignupSelection.tsx
client/src/pages/Signup/SignupTerm.tsx

`fe-feat/url` -> `fe`
- 서버 주소 변경

!BREAKING CHANGE: 배포 서버 url 변경

---

client/src/layout/Header/index.tsx

`fe-feat/Headerlogin` -> `fe`
- 토큰 검증 구현
- 유효 토큰 검증 구현

Fix: 헤더 로그아웃 검증 수정

---

client/src/pages/Cart.tsx
client/src/pages/Payment/CheckoutChang.tsx
client/src/pages/Payment/Payment.tsx
client/src/pages/Payment/PaymentConfirm.tsx
client/src/pages/Payment/PaymentUserinfo.tsx
client/src/pages/Payment/Paymentpayinfo.tsx

`fe-feat/paymentgood` -> `fe`
- 결제 완료페이지에서 orders로 post 구현
- 결제 페이지 props 구조 수정
- 결제 유저정보 get 구현

Fix : 결제 기능 완료

---

server/src/main/java/com/codestates/julsinsa/item/controller/ItemController.java
server/src/main/java/com/codestates/julsinsa/item/dto/ItemDto.java
server/src/main/java/com/codestates/julsinsa/item/entity/Item.java
server/src/main/java/com/codestates/julsinsa/item/mapper/ItemMapper.java
server/src/main/java/com/codestates/julsinsa/item/repository/ItemRepository.java
server/src/main/java/com/codestates/julsinsa/item/service/ItemService.java
server/src/main/java/com/codestates/julsinsa/member/controller/MemberController.java

Branch
Be-feat/member -> be
변경 사항
술 CRUD 완성
유의사항
관리자 페이지가 없으므로 관리자 페이지가 생기면 추가 삭제 수정 등에 추가 권한을 부여할 것임

feat : 술 CRUD 완성

---

client/src/components/Chat/ChatComponent.tsx
client/src/hooks/useAxiosAll.tsx
client/src/pages/Login/Login.tsx
client/src/pages/Mypage/ChangeInfoPage.tsx
client/src/pages/Signup/SignupInput.tsx
client/src/pages/Signup/SignupTerm.tsx

`fe-feat/responsive-settings/198` -> `fe`
- 로그아웃 상태처리 시 로그인 창 이동후 알림 설정
- 로그인, 회원가입, 개인정보 수정 페이지 반응형 수정 및 추가 적용

Fix: 반응형 수정 및 로그아웃 상태시 알림 설정

---

client/src/layout/Header/index.tsx
client/src/pages/Mypage/LikeListPage.tsx
client/src/pages/Mypage/OrderListPage.tsx
client/src/pages/Place.tsx

- 헤더 연결주소 변경( 찜리스트, 주문내역, 개인정보수정페이지)
- 찜리스트: 스타일 수정
- 주문내역: 스타일 수정, review연결
- 지도: 배포서버 주소 연결.

Feat: 헤더 연결주소 변경 및 review연결

---

server/src/main/java/com/codestates/julsinsa/auth/dto/LoginDto.java
server/src/main/java/com/codestates/julsinsa/auth/filter/JwtAuthenticationFilter.java
server/src/main/java/com/codestates/julsinsa/auth/filter/JwtVerificationFilter.java
server/src/main/java/com/codestates/julsinsa/auth/handler/OAuth2MemberSuccessHandler.java
server/src/main/java/com/codestates/julsinsa/auth/jwt/JwtTokenizer.java
server/src/main/java/com/codestates/julsinsa/auth/userdetails/MemberDetailsService.java
server/src/main/java/com/codestates/julsinsa/cart/controller/CartController.java
server/src/main/java/com/codestates/julsinsa/cart/dto/CartDto.java
server/src/main/java/com/codestates/julsinsa/config/PasswordEncoderConfiguration.java
server/src/main/java/com/codestates/julsinsa/config/SecurityConfiguration.java
server/src/main/java/com/codestates/julsinsa/helper/email/HtmlEmailSendable.java
server/src/main/java/com/codestates/julsinsa/item/controller/ItemController.java
server/src/main/java/com/codestates/julsinsa/item/dto/ItemDto.java
server/src/main/java/com/codestates/julsinsa/item/entity/Item.java
server/src/main/java/com/codestates/julsinsa/item/repository/ItemRepository.java
server/src/main/java/com/codestates/julsinsa/item/service/ItemService.java
server/src/main/java/com/codestates/julsinsa/member/controller/MemberController.java
server/src/main/java/com/codestates/julsinsa/member/dto/EmailRequest.java
server/src/main/java/com/codestates/julsinsa/member/dto/FindDto.java
server/src/main/java/com/codestates/julsinsa/member/entity/Member.java
server/src/main/java/com/codestates/julsinsa/review/controller/ReviewController.java
server/src/main/java/com/codestates/julsinsa/review/dto/ReviewDto.java
server/src/main/java/com/codestates/julsinsa/review/service/ReviewService.java

Branch
be-feat/member -> be
변경 사항
코드 정리

refactor : 의미 없는 로직 제거 , 코드 정리

---

client/src/components/AlcoholDetailPage/AlcohoIItemReview.tsx
client/src/components/AlcoholDetailPage/AlcohoItemContent.tsx
client/src/components/AlcoholDetailPage/AlcoholItemBuy.tsx
client/src/components/AlcoholDetailPage/ReviewList.tsx
client/src/pages/ReviewEdit.tsx
client/src/services/api/axiosInstance.ts
client/src/types/AlcholInterfaces.ts

- 리뷰 생성 및 수정 id 값 다르게 받기
- 리뷰 수정 할 때 이미지 변경할 경우, 기존 이미지 삭제 후 새로운 이미지 덮어씌우기
- 리뷰 수정 할 때 이미지 변경하지 않을 경우, 기존 이미지 사용
- 리뷰 생성 및  수정 시 페이지 이동 처리
- 아이템 추가 시 장바구니 페이지로 이동할 지 않할 지

Fix: 리뷰 생성 및 수정 처리

---

client/src/pages/Home.tsx
client/src/pages/Homelayout.tsx

`fe-feat/mainfix` -> `fe`
- 메인페이지 css 수정

fix: 메인페이지 수정

---

client/src/pages/Mypage/LikeListPage.tsx
client/src/pages/Mypage/OrderListPage.tsx

- 주문내역페이지: 주문취소기능구현
- 찜리스트: 가격 정규표현식 적용

Feat: 주문취소기능 구현 및 가격 정규표현식 적용

---

client/src/hooks/useAxiosAll.tsx
client/src/pages/Login/Login.tsx
client/src/pages/Signup/SignupInput.tsx
client/src/pages/Signup/SignupSelection.tsx
client/src/pages/Signup/SignupTerm.tsx

Fix: url 수정 env

---

client/src/components/Chat/ChatComponent.tsx
client/src/hooks/useAxiosAll.tsx
client/src/pages/Mypage/ChangeInfoPage.tsx
client/src/pages/Signup/SignupInput.tsx

`fe-feat/bugfix/208` -> `fe`
- 회원가입 특수문자 비밀번호 사용 가능 수정
- 회원가입 이메일 인증 요청 버튼 모바일 및 기타 버젼에 좀 더 어울리게 위치 수정
- 개인정보 수정페이지 접근시 비밀번호 인증 로직 추가
- chat gpt 위치 수정 및 onkeydown 설정 추가

Feat: 회원가입, 개인정보 수정 페이지 버그 수정 및 스타일 수정

---

server/src/main/java/com/codestates/julsinsa/global/utils/MemberUtils.java

refactor : 로그인한 사용자를 찾는 컴포넌트 추가

---

client/src/pages/Place.tsx

Feat: 지도랑 결제연결 

---

client/src/pages/Login/Login.tsx

fe-feat/exptime
- 한국시간 기준 exp, iat 로컬 저장

Fix: 한국시간 시간 기준 exp iat 로컬 저장

---

client/src/layout/Header/index.tsx
client/src/pages/Home.tsx
client/src/pages/Homelayout.tsx
client/src/pages/Payment/Payment.tsx
client/src/pages/Payment/Paymentpayinfo.tsx
client/src/pages/Place.tsx

`fe-feat/Homepayment` -> `fe`
- 지도 데이터 수정
- 홈화면 수정
- 헤더 반응형 및 회원가입 삭제

Fix: 홈화면 결제화면 수정

---

client/src/components/AlcoholDetailPage/AlcoholItemBuy.tsx
client/src/layout/Header/index.tsx
client/src/pages/Home.tsx
client/src/pages/Homelayout.tsx
client/src/pages/Payment/Payment.tsx
client/src/pages/Payment/Paymentpayinfo.tsx
client/src/pages/Place.tsx

`fe-feat/itemcartpay` -> `fe`
- 아이템-> 장바구니 바로 결제 기능 구현

Fix 아이템 바로결제 기능 구현

---

client/src/components/AlcoholDetailPage/AlcohoItemContent.tsx
client/src/components/AlcoholDetailPage/AlcoholItemBuy.tsx
client/src/components/AlcoholPage/AlcoholList.tsx
client/src/components/AlcoholPage/AlcoholListItem.tsx
client/src/components/AlcoholPage/Pagination.tsx
client/src/components/AlcoholPage/SortingUtils.tsx
client/src/components/Common/ClickFavoriteItem.tsx
client/src/components/Common/PriceDisplay.tsx
client/src/components/Common/ReviewRating.tsx
client/src/pages/Alcohol.tsx
client/src/services/api/itemAPI.ts

`fe-feat/refactor/#220` -> `fe`
- 불필요한 주석 삭제
- 크라코 경로로 변경
- 버튼 스타일 변경

Refactor: 주류 페이지 리팩토링

---

client/src/components/Chat/ChatComponent.tsx
client/src/components/Common/Button.tsx
client/src/hooks/useAxiosAll.tsx
client/src/pages/Login/FindEmail.tsx
client/src/pages/Login/FindPassword.tsx
client/src/pages/Login/Login.tsx
client/src/pages/Mypage/ChangeInfoPage.tsx
client/src/pages/Signup/SignupInput.tsx
client/src/pages/Signup/SignupSelection.tsx
client/src/pages/Signup/SignupTerm.tsx

fe-feat/fix-remove -> fe
- 모바일 반응형 디자인 수정
- 불필요한 주석 및 콘솔 삭제
- 코드 정리

Fix: 디자인 반응형 수정 및 불필요한 라인 삭제 및 정리

---

client/src/layout/Header/index.tsx
client/src/pages/Cart.tsx
client/src/pages/Home.tsx
client/src/pages/Payment/Payment.tsx
client/src/pages/Payment/PaymentConfirm.tsx
client/src/pages/Payment/Paymentitemlist.tsx
client/src/pages/Payment/Paymentpayinfo.tsx
client/src/pages/Payment/Progress.tsx
client/src/pages/Place.tsx

`fe-feat/bugfix` -> `fe`
- 아이템-결제 바로가기 구현
- 결제페이지 지도 연동 구현

Fix: 여러 버그사항 수정

---

client/src/pages/Map.tsx
client/src/pages/Mypage/LikeListPage.tsx
client/src/pages/Mypage/OrderListPage.tsx
client/src/pages/Place.tsx

- 찜리스트: 수량표시 제거
- 주문내역: 주문취소 버튼 비활성화작용
- 지도: 불필요한 주석 제거

Feat: 주문취소버튼 비활성화 및 수량표시 제거

---

client/src/pages/Mypage/OrderListPage.tsx
client/src/pages/Place.tsx

`fe-feat/map` -> `fe`
- 주문내역: "주문조회기간"에서 "주문기간조회"으로 내용변경
- 지도: 마커 클릭시 매장명 알수있게 설정.

Feat: 마커클릭시 매장명 알수있게 설정

---

client/src/pages/Place.tsx

`fe-feat/map-map` -> `fe`
- 지도: 필요없는 border design 삭제

Design: 필요없는 border 삭제

---

client/src/pages/Mypage/ChangeInfoPage.tsx

- 개인정보수정페이지 디자인 수정
- 버튼 컴포넌트 적용
- 제목 부각되게 수정
- 표 왼쪽정렬로 수정
- 비밀번호확인에서 비밀번호변경확인으로 수정

Design: button 컴포넌트 적용 및 세부적인 디자인 수정

---

server/src/main/java/com/codestates/julsinsa/auth/userdetails/MemberDetailsService.java
server/src/main/java/com/codestates/julsinsa/cart/controller/CartController.java
server/src/main/java/com/codestates/julsinsa/cart/dto/CartDto.java
server/src/main/java/com/codestates/julsinsa/cart/dto/ItemCartDto.java
server/src/main/java/com/codestates/julsinsa/cart/service/CartService.java
server/src/main/java/com/codestates/julsinsa/member/entity/Member.java

Branch
be-feat/member -> be
변경 사항
Cart Patch 기능 구현
로그인시 passwordIssued 헤더에 담기게 수정

fix : Cart Patch 기능 구현 , 로그인시 passwordIssued 헤더에 담기게 수정

---

client/src/pages/Mypage/LikeListPage.tsx
client/src/pages/Mypage/OrderListPage.tsx

- 찜리스트페이지 필요없는 주석 제거 및 정리
- 주문내역페이지 필요없는 주석 제거 및 정리

Comment: 필요없는 주석 제거 및 정리

---

client/src/layout/Header/Logoutmodal.tsx
client/src/layout/Header/index.tsx
client/src/pages/Cart.tsx
client/src/pages/Home.tsx
client/src/pages/Payment/CheckoutChang.tsx
client/src/pages/Payment/Payment.tsx
client/src/pages/Payment/PaymentConfirm.tsx
client/src/pages/Payment/PaymentUserinfo.tsx
client/src/pages/Payment/Paymentitemlist.tsx
client/src/pages/Payment/Paymentpayinfo.tsx
client/src/pages/Payment/Progress.tsx
client/src/pages/Place.tsx

`fe-feat/Comment`-> `fe`
- 필요없는 주석 제거 및 정리
- 주문내역페이지 필요없는 주석 제거 및 정리
- 장바구니 patch로 뒤로가기/ 결제하기 시 서버에 patch
- 결제피이지 결제컨테이너 수정
- 결제페이지 픽업 css 수정
- 결제페이지 navigate로 props 내려줌
- 결제페이지 disabled 기능 추가
- 결제 완료 페이지 - 홈 버튼 추가
- 로그아웃 모달창 css 수정
- 홈화면 css 수정중
- 홈화면 css 아직 고치는 중

Comment: 파일수정 및 필요없는 코드 삭제

---

client/src/pages/ReviewEdit.tsx

Fix: 페이지 이동 수정

---

client/src/pages/Map.tsx
client/src/pages/Mypage/OrderListPage.tsx

- Map: handleChoice뜨던 버그수정
- OrderListPage: 픽업완료시에만 후기버튼 가능하게 수정

Feat: 에러수정 및 후기버튼 기능 수정

---

client/src/pages/Mypage/ChangeInfoPage.tsx
client/src/pages/Signup/SignupInput.tsx

fe-feat/fix-func
- 수정페이지 버그 수정
- 비밀번호 특수문자 포함 유효성 검사 추가

Fix: 버그 수정 및 유효성 추가

---

server/src/main/java/com/codestates/julsinsa/auth/handler/OAuth2MemberSuccessHandler.java

fix : Oauth2 리다이렉트 경로 변경

---

client/src/pages/Mypage/OrderListPage.tsx

- OrderListPage: 주문내역 최신순으로 나열기능 추가

Feat: 주문내역 최신순으로 나열기능 추가

---

client/src/pages/Login/Login.tsx
client/src/pages/Signup/SignupSelection.tsx

fe-feat/naver-Oauth -> fe
- 페이스북 오어스에서 네이버 오어스로 변경

Fix: 네이버 오어스 수정

---

server/src/main/java/com/codestates/julsinsa/auth/handler/OAuth2MemberSuccessHandler.java
server/src/main/resources/db/h2/data.sql

Feat : 네이버 OAuth2 구현

---

client/src/components/AlcoholDetailPage/AlcohoItemContent.tsx
client/src/types/AlcholInterfaces.ts

Fix: 데이터 변경

---

client/src/pages/Mypage/LikeListPage.tsx
client/src/pages/Mypage/OrderListPage.tsx

- OrderListPage: 주문취소시 버튼 사라지게 기능 구현, 페이지네이션 오류 수정, 상품목록 클릭시 주류 상세페이지 연결
- LikeListPage: 상품사진, 상품목록 클릭시 주류 상세페이지 연결

Feat: 마이페이지 주류상세페이지 연결 등 기능 구현

---

client/src/pages/Home.tsx
client/src/pages/Homelayout.tsx

`fe-feat/maindesign` -> `fe`
- 메인페이지 디자인 변경

Design: 메인페이지 css 수정

---

server/src/main/java/com/codestates/julsinsa/auth/filter/JwtAuthenticationFilter.java
server/src/main/java/com/codestates/julsinsa/auth/handler/OAuth2MemberSuccessHandler.java
server/src/main/java/com/codestates/julsinsa/member/service/MemberService.java

Fix : 토큰 시간 수정

---

client/src/services/api/axiosInstance.ts
client/src/services/api/itemAPI.ts

Refactor: 코드 정리

---

client/src/pages/Mypage/LikeListPage.tsx
client/src/pages/Mypage/OrderListPage.tsx

- LikeListPage: 찜리스트 내역없을때 없음 알리는 문구 추가
- OrderListPage: 리스트 반복 에러 수정
-OrderListPage: 페이지네이션 에러 다시 미해결

Feat: 찜리스트 목록없음 알림 기능 구현 및 주문내역페이지 에러 수정

---

client/src/pages/Cart.tsx
client/src/pages/Payment/PaymentConfirm.tsx
client/src/pages/Payment/Paymentpayinfo.tsx
client/src/pages/Place.tsx
client/src/redux/slice/store.tsx

`fe-feat/cartdelete` -> `fe`
- 결제시 장바구니에 결제 항목 삭제

fix: 결제시 장바구니 삭제

---

client/src/pages/Mypage/LikeListPage.tsx
client/src/pages/Mypage/OrderListPage.tsx

- OrderListPage: 페이지네이션 오류 완전 해결
- LikeListPage: 개발자도구에 table관련 오류 뜨던 것 해결

Fix: 페이지네이션 오류 해결

---

client/src/hooks/useAxiosAll.tsx
client/src/pages/Login/FindPassword.tsx
client/src/pages/Mypage/ChangeInfoPage.tsx
client/src/pages/Signup/SignupInput.tsx
client/src/pages/Signup/SignupTerm.tsx

: fe-feat/oauthbugfix -> fe
- 기타 버그 수정

fix: 기타 버그 수정

---

client/src/hooks/useAxiosAll.tsx
client/src/pages/Signup/SignupInput.tsx
client/src/pages/Signup/SignupTerm.tsx

fe-feat/oauthbugfix -> fe
- 회원가입 뒤로가기 버튼 수정
- header 수정

Fix: text 수정 및 header 수정

---

client/src/components/AlcoholDetailPage/AlcoholItemBuy.tsx
client/src/components/AlcoholPage/ItemSearch.tsx
client/src/components/AlcoholPage/Pagination.tsx
client/src/pages/Alcohol.tsx
client/src/services/api/axiosInstance.ts
client/src/services/api/itemAPI.ts
client/src/styles/GlobalStyle.ts
client/src/types/AlcholInterfaces.ts

Feat: 검색 기능 추가

---

client/src/pages/Mypage/ChangeInfoPage.tsx
client/src/pages/Signup/SignupInput.tsx
client/src/pages/Signup/SignupTerm.tsx

Fix: 긴급 수정

---

server/src/main/java/com/codestates/julsinsa/chatai/config/ChatGptConfig.java
server/src/main/java/com/codestates/julsinsa/member/service/MemberService.java
server/src/main/java/com/codestates/julsinsa/order/service/OrderService.java

Fix : 결제시 재고변경 , 이메일 인증 비동기 -> 동기

Fix : 결제시 재고변경 , 이메일 인증 비동기 -> 동기

---

client/src/components/AlcoholPage/ItemSearch.tsx
client/src/components/Common/ClickFavoriteItem.tsx
client/src/pages/Alcohol.tsx

Refactor: 주석 제거

---

client/src/pages/Map.tsx

`fe-feat/map` -> `fe`
- map: 커스텀오버레이 css변경

Design: map 커스텀오버레이 css변경

---

server/src/main/java/com/codestates/julsinsa/chatai/config/ChatGptConfig.java
server/src/main/java/com/codestates/julsinsa/chatai/service/ChatGptService.java

Fix : gpt api키 위치 수정

---

client/src/pages/Cart.tsx
client/src/pages/Home.tsx
client/src/pages/Homelayout.tsx
client/src/pages/Payment/CheckoutChang.tsx
client/src/pages/Payment/Payment.tsx
client/src/pages/Payment/PaymentConfirm.tsx
client/src/pages/Payment/Paymentpayinfo.tsx

`fe-feat/fixadd` -> `fe`
- 홈 화면 폰트 크키 수정
- 네비게이션 홈말고 login 으로 수정
- 결제 페이지 지도 크기 조정
- 결제 완료페이지 뒤로가기 대신 홈으로 변경
- 콘솔 삭제

Fix: 추가 수정

---

client/src/hooks/useAxiosAll.tsx
client/src/pages/Login/Login.tsx
client/src/pages/Mypage/ChangeInfoPage.tsx
client/src/pages/Signup/SignupInput.tsx

fe-feat/oauth-style -> fe
- 오어스 버그 수정
- 유효성 힌트 하단 방식 변경

Fix: 오어스 버그 수정

---

client/src/pages/Place.tsx

`fe-feat/map` -> `fe`
- map: 선택박스 미선택시와 선택시 차이 수정, 첫화면 상단부 고정 기능 추가

Feat: 지도페이지 선택박스부분수정, 첫화면 상단부고정 기능 추가

---

client/src/components/AlcoholPage/ItemSearch.tsx
client/src/pages/Alcohol.tsx

Fix: 상품 검색 총 개수 수정

---

client/src/pages/Payment/Payment.tsx

`fe-feat/payfix` -> `fe`
- 상품 목록에서 구매버튼으로 바로 이동시 주문내역으로 넘어가지 않던 부분 수정

Fix: 아이템리스트->결제페이지 수정

---

client/src/components/AlcoholPage/ItemSearch.tsx
client/src/pages/Alcohol.tsx

Fix: 주류 검색 수정

---

client/src/pages/Mypage/ChangeInfoPage.tsx
client/src/pages/Signup/SignupInput.tsx

fe-feat/fix-changeinfo -> fe
- 개인정보 수정 - 전화번호 유효성 검사 추가 (11자리 모두기입)

fix: 전화번호 유효성 검사 추가

---

client/src/components/Chat/ChatComponent.tsx
client/src/components/HelpCenter/AnswerContainer.tsx
client/src/pages/HelpCenter.tsx
client/src/pages/Login/FindEmail.tsx
client/src/pages/Login/FindPassword.tsx
client/src/pages/Login/Login.tsx
client/src/pages/Signup/SignupInput.tsx

fe-feat/fix-bug-style -> fe
- gpt 버그수정
- 기타 반응형 수정

fix: 버그 수정 및 스타일 수정

---

client/src/components/AlcoholDetailPage/AlcohoIItemReview.tsx
client/src/components/AlcoholDetailPage/AlcohoItemContent.tsx
client/src/components/AlcoholDetailPage/AlcoholItemBuy.tsx
client/src/components/AlcoholDetailPage/ReviewList.tsx
client/src/components/AlcoholPage/AlcoholList.tsx
client/src/components/AlcoholPage/AlcoholListItem.tsx
client/src/components/AlcoholPage/ItemSearch.tsx
client/src/components/AlcoholPage/Pagination.tsx
client/src/components/AlcoholPage/SortingUtils.tsx
client/src/components/Common/ReviewRating.tsx
client/src/pages/Alcohol.tsx

Refactor: 주류 리스트 및 상세 웹 반응형 수정

---

client/src/components/AlcoholDetailPage/AlcoholItemBuy.tsx

Fix: 상품 디테일 수정

---

client/src/components/Chat/ChatComponent.tsx
client/src/pages/Login/FindEmail.tsx
client/src/pages/Login/FindPassword.tsx
client/src/pages/Login/Login.tsx
client/src/pages/Signup/SignupInput.tsx
client/src/pages/Signup/SignupSelection.tsx
client/src/pages/Signup/SignupTerm.tsx

fe-feat/fix-bug-style -> fe
- 반응형 스타일 수정 2차

Fix: 스타일 수정

---

client/src/components/Chat/ChatComponent.tsx

fe-feat/fix-bug-style -> fe
- 반응형 스타일 수정 2차

Fix: gpt 색상 gray로 변경

---

client/src/layout/Header/index.tsx
client/src/pages/Cart.tsx
client/src/pages/Homfirst.tsx
client/src/pages/Payment/Payment.tsx
client/src/pages/Payment/PaymentUserinfo.tsx
client/src/pages/Payment/Paymentitemlist.tsx
client/src/pages/Payment/Paymentpayinfo.tsx
client/src/pages/Payment/Progress.tsx

`fe-feat/homecss` -> `fe`
###변경사항
- 반응형 추가

fix: 반응형 추가

---

client/src/layout/Header/index.tsx
client/src/pages/ReviewEdit.tsx
client/src/styles/GlobalStyle.ts

Design: 후기 페이지 디자인 수정

---

client/src/layout/Header/index.tsx
client/src/styles/GlobalStyle.ts

Fix: 헤더 오버 수정

---

client/src/components/AlcoholPage/SortingUtils.tsx
client/src/layout/Header/index.tsx
client/src/pages/Alcohol.tsx

Fix: 헤더 추가 수정
